#!/usr/bin/env bash

set -e

if ! command -v cargo-depgraph >/dev/null 2>&1; then
    cargo install cargo-depgraph
fi

graph_file=target/crate-graph.html

cargo depgraph \
    --workspace-only \
    --offline \
    --root=zed,agent_ui,agent \
    --dedup-transitive-deps \
    | dot -Tsvg > $graph_file

echo "open $graph_file"
open $graph_file
